1.Array of 3x3x3

In [5]:
import numpy as np
x = np.random.random((3,3,3))
print(x)
Copy
Sample Output:

[[[1 2 3]
  [3 4 6]
  [2 4 5]]

 [[5 6 8]
  [7 8 5]
  [2 4 5]]

 [[1 2 7]
  [3 4 8]
  [2 0 6]]]


2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. Normalize a 5x5 random matrix

In [9]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.81970406 0.05483682 1.         0.37112806 0.45592156]
 [0.90855509 0.63653878 0.6105604  0.77917244 0.88591471]
 [0.27354432 0.58034562 0.55732158 0.01489262 0.7267452 ]
 [0.88425116 0.07184446 0.26871738 0.30694552 0.10939472]
 [0.         0.26331849 0.46228307 0.54206049 0.02134614]]


5. How to find common values between two arrays?

In [10]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


6.How to get the dates of yesterday, today and tomorrow?

In [11]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


7. Consider two random array A and B, check if they are equal

In [12]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False



8.Create random vector of size 10 and replace the maximum value by 0

In [13]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.08407751 0.2757856  0.3088992  0.10490392 0.52120233 0.57934894
 0.44046974 0.29909449 0.         0.17910574]


9. How to print all the values of an array?

In [14]:
print(Z)

[0.08407751 0.2757856  0.3088992  0.10490392 0.52120233 0.57934894
 0.44046974 0.29909449 0.         0.17910574]



10.Subtract the mean of each row of a matrix

In [16]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.33089468, -0.44094117, -0.28800089, -0.44062292,  0.38690861,
         0.39944806,  0.24817677,  0.26600388,  0.38401536, -0.18409303],
       [-0.32752553, -0.37942932,  0.54360954,  0.24913362,  0.41928861,
        -0.04763086, -0.31460841,  0.21319864, -0.14710319, -0.2089331 ],
       [-0.00880017,  0.17624812,  0.41747066, -0.31074536, -0.28988816,
         0.44836862, -0.37145449,  0.33946788, -0.14846017, -0.25220692],
       [ 0.19221431,  0.27065377, -0.46428723,  0.13033084, -0.35641146,
         0.09705429,  0.0229049 ,  0.23439934, -0.20780224,  0.08094347],
       [-0.34721579, -0.19721791, -0.15587635,  0.10483848, -0.03473352,
         0.49723934,  0.27759504, -0.25873384,  0.4929372 , -0.37883265]])

11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [17]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[4. 4. 3. 1. 2. 5. 2. 2. 3. 4.]


12.How to get the diagonal of a dot product?


In [18]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([35, 25, 98])

13.How to find the most frequent value in an array?

In [19]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[4 9 3 4 0 0 7 3 6 1 9 1 9 1 3 4 6 2 2 8 4 6 1 3 6 5 5 0 3 1 9 8 6 5 9 6 4
 6 5 5 9 2 1 5 2 0 7 8 2 9]
rank: 6



14.How to get the n largest values of an array

In [20]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


15.How to create a record array from a regular array?

In [22]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
